import Head from "next/head";
import Navbar from "../../../components/Navbar/navbar";
import Categories from "../../../components/CategoriesBar/categories";
import styles from "./categories.module.scss";
import Sidebar from "../../../components/CategoryPage/sidebar";
import Product from "../../../components/CategoryPage/product";
import useWindowSize from "../../../hooks/useWindowSize";
import Navbar__resp from "../../../components/Navbar/navbar__resp";
import { useRouter } from "next/router";

function index({ categories }) {
  const size = useWindowSize();
  const router = useRouter();
  const { url } = router.query;
  console.log(categories);
  return (
    <div className={styles.categories} categories={categories}>
      <Head>
        <title>Amazon Remade by Allego</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      {size.width > 768 ? <Navbar /> : <Navbar__resp />}
      <Categories />
      <div className={styles.body}>
        <div className={styles.sidebar}>
          <Sidebar />
        </div>
        <div className={styles.main}>
          {categories.map((category, id) => (
            <div>
              <Product category={category} />
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default index;

export async function getServerSideProps({ params }) {
  const categories = await fetch(
    `https://fakestoreapi.com/products/category/${params.url}`
  ).then((res) => res.json());
  return {
    props: {
      categories,
    },
  };
}
