import Head from "next/head";
import Navbar from "../components/Navbar/navbar";
import styles from "../styles/constants.module.scss";
import UseWindowSize from "../hooks/useWindowSize";
import Navbar__resp from "../components/Navbar/navbar__resp";
import Categories from "../components/CategoriesBar/categories";
import Gallery from "../components/Slider/slider";
import Grid from "../components/Grid/grid";
import Link from "next/link";
import {
  imageSources1,
  imageSources2,
  imageSources3,
  imageSources4,
  singleImage1,
  singleImage2,
  singleImage3,
  singleImage4,
} from "../styles/imageSources";
import Populars from "../components/Populars/populars";
import GridResp from "../components/Grid/grid_resp";
import Login from "../components/Login/login";
import { useSession, signIn, signOut } from "next-auth/react";
import Foobar from "../components/Footbar/foobar";


export default function Home({ products }) {
  const size = UseWindowSize();
  const { data: session } = useSession()
  console.log(size);
  const headlines1 = ["Headsets", "Keyboards", "Mice", "Chairs"];
  const headlines2 = ["Computers", "Video Games", "Baby", "Games"];
  const headlines3 = ["Electronics", "Fashion", "Toys", "Beauty"];
  const headlines4 = ["Sweatshirts", "Joggers", "Cardigans", "Easy tees"];
  const headlineConcated = headlines1.concat(
    headlines2,
    headlines3,
    headlines4
  );
  return (
    <div>
      <Head>
        <title>Amazon Remade by Allego</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      {size.width > 768 ? <Navbar /> : <Navbar__resp />}
      
       <Categories />
     
      <div className={styles.container}>
        <Gallery />
        
        {size.width > 768 ? (
          <div className={styles.productContainer}>
           
              <Grid
                headline="Gaming accesories"
                images={imageSources1}
                headlines={headlines1}
                category="electronics"
              />
           

           
            <Grid
              headline="Comfy styles for her"
              images={imageSources4}
              headlines={headlines4}
              category="men's clothing"
            />

            <Grid
              headline="Holiday Gifts"
              images={imageSources3}
              headlines={headlines3}
              category="jewelery"
            />

            {session ? (
               <Grid
                headline="Holiday Gifts"
                images={imageSources2}
                headlines={headlines2}
                category="women's clothing"
              />
            ) : (<Login />)}
            

            <Grid
              headline="Comfy styles for her"
              singleImages={singleImage1}
              category="electronics"
            />

            <Grid
              headline="Comfy styles for her"
              singleImages={singleImage2}
              category="men's clothing"
            />

            <Grid
              headline="Comfy styles for her"
              singleImages={singleImage3}
              category="jewelery"
            />

            <Grid
              headline="Comfy styles for her"
              singleImages={singleImage4}
              category="women's clothing"
            />
          </div>
        ) : (
          <div>
              <GridResp
                can="https://cdn.flashtalking.com/xre/588/5888516/3655206/image/3655206.gif?460613880"
                headlines={headlineConcated}
              />
              {(size.width<768 && !session) && 
                <Login />
              }


              <div className={styles.productContainer}>
              
              <Grid
                headline="Gaming accesories"
                images={imageSources1}
                headlines={headlines1}
                category="electronics"
              />

              {(size.width < 769 && session) ?
                ( <Grid
                  headline="Holiday Gifts"
                  images={imageSources2}
                  headlines={headlines2}
                  category="men's clothing"
                />) : ("")
              }
              {(size.width < 769 && !session && size.width > 600) &&
                (  <Login/>) 
              }
                <Grid
                  headline="Holiday Gifts"
                  images={imageSources3}
                  headlines={headlines3}
                  category="jewelery"
                />

              <Grid
                headline="Comfy styles for her"
                images={imageSources4}
                headlines={headlines4}
                category="men's clothing"
              />

              <Grid
                headline="Comfy styles for her"
                singleImages={singleImage1}
                category="women's clothing"
              />

              <Grid
                headline="Comfy styles for her"
                singleImages={singleImage2}
                category="men's clothing"
              />

              <Grid
                headline="Comfy styles for her"
                singleImages={singleImage3}
                category="jewelery"
              />

              <Grid
                headline="Comfy styles for her"
                singleImages={singleImage4}
                category="electronics"
              />
              </div>
          
          </div>
        )}
        <div className={styles.populars}>
          <Populars products={products}  />
        </div>
        {size.width < 1024 && 
        <Foobar />
        } 
      </div>
      {size.width > 1023 ? 
      <div className={styles.foobar}>
        <Foobar />
      </div>
      : " "}
    </div>
  );
}

export async function getServerSideProps(context) {
  const products = await fetch("https://fakestoreapi.com/products").then(
    (res) => res.json()
  );
  return {
    props: {
      products,
    },
  };
}




