import Head from 'next/head'
import Navbar from '../components/Navbar/navbar'
import styles from '../styles/constants.module.scss'
import useWindowSize from '../hooks/useWindowSize'
import Navbar__resp from '../components/Navbar/navbar__resp'
import Categories from'../components/CategoriesBar/categories'
import Gallery from '../components/Slider/slider'
import Product from '../components/Product/product'
import {imageSources1,imageSources2,imageSources3,imageSources4,
        singleImage1,singleImage2,singleImage3,singleImage4} from '../styles/imageSources'
import Populars from '../components/PopularsCarousel/populars'

export default function Home({products}) {
  const size = useWindowSize();
  const headlines1=["Headsets","Keyboards","Computer mice","Chairs"]
  const headlines2=["Computers & Accesories","Video Games","Baby","Toys & Games"]
  const headlines3=["Electronics","Fashion","Toys","Beauty"]
  const headlines4=["Sweatshirts","Joggers","Cardigans","Easy tees"]
  return (
    <div  >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {size.width > 768 ? (<Navbar/>) : (<Navbar__resp />) }
      <Categories/>
      <div className={styles.container}>
        <Gallery/>
        <div className={styles.productContainer}>
          <Product 
            headline="Gaming accesories" 
            images={imageSources1}
            headlines={headlines1}
          />

          <Product 
            headline="Shop by Category" 
            images={imageSources2}
            headlines={headlines2}
          />

          <Product 
            headline="Holiday Gifts" 
            images={imageSources3}
            headlines={headlines3}
          />

          <Product 
            headline="Comfy styles for her" 
            images={imageSources4}
            headlines={headlines4}
          />

          <Product 
            headline="Comfy styles for her" 
            singleImages={singleImage1}
          />

          <Product 
            headline="Comfy styles for her" 
            singleImages={singleImage2}
          />

          <Product 
            headline="Comfy styles for her" 
            singleImages={singleImage3}
          />

          <Product 
            headline="Comfy styles for her" 
            singleImages={singleImage4}
          />
        </div>
        <Populars products={products}/>
       
      </div>

     {console.log(products)}

    </div>
  )
}

export async function getServerSideProps(context){
  const products = await fetch("https://fakestoreapi.com/products").then(
    (res) => res.json()
  );
  return {
    props : {
      products,
    },
  };
}



//https://fakestoreapi.com/products